-- 070_ai_interview_questions.sql
-- Trilingual interview questions generated by Gemini Pro from a candidate's
-- CV analysis + the job posting. Stored as a single JSONB blob alongside the
-- candidate row so reads are one column away.
--
-- Shape (validated app-side via Zod):
--   {
--     "generated_at": "2026-04-19T12:34:56.789Z",
--     "model": "gemini-3.1-pro-preview",
--     "ru": [{"question": "...", "rationale": "...",
--             "focus": "strength_probe|gap_probe|role_fit|behavioral|signal_check"}, ...],
--     "uz": [...],
--     "en": [...]
--   }
--
-- Read strategy: app-side via pickLocalizedArray on `<blob>.<viewer_locale>`.

alter table candidates
  add column if not exists ai_interview_questions jsonb;

comment on column candidates.ai_interview_questions is
  'Trilingual interview questions generated by Gemini. Shape: { generated_at, model, ru:[{question,rationale,focus}], uz:[...], en:[...] }. Null = not yet generated.';

create index if not exists candidates_has_questions_idx
  on candidates ((ai_interview_questions is not null))
  where ai_interview_questions is not null;
